### ISSUE TITLE
Support for San Francisco and Frankfurt locations?

### ISSUE THREAD

**Issue by mikeroySoft** [ryanpq/do-wpc#1]
I notice I am only given the options of 
1.) NYC3 - New York, NY
2.) AMS2 - Amsterdam, NE
3.) LON1 - London, UK
4.) SGP1 - Singapore

I don't seem to see San Francisco or Frankfurt there?

**Comment by ryanpq** [comment]
Frankfurt region has now been added and SFO1 and FRA1 both appear in the menu options.
